version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: imagedb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Porta principal do LocalStack
      - "4571:4571"  # Porta para Lambda (se necessário)
    environment:
      - SERVICES=s3,lambda,apigateway
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080  # Interface Web do LocalStack (opcional)
      - DEBUG=1
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./uploads:/tmp/uploads  # Diretório para uploads temporários

volumes:
  postgres-data:
